### ISSUE TITLE
Ignore all whitespace within a Lexer?

### ISSUE THREAD

**Issue by ChrisMissal** [plioi/parsley#11]
## Question

I'm wondering if there's a way to ignore whitespace in an easier fashion than I'm currently doing it. I'm building an app to extract data from a log file (so I'll end up with dozens of single line lexers (each line has a different format)

## Current Implementation

Here's what I'm currently doing in my lexers:

```csharp
public FileReceivedLexer()
  : base(OpenBrace, TimeSpan, CloseBrace, Whitespace, Subject, Whitespace, Received, Whitespace, Number, Whitespace, new Keyword("files"))
{
}
```

Is there a way to avoid so many `Whitespace` references? Or do you have some advice on how I could trim these down a bit?

**Bonus:** Every line starts with `[00:12:34.567]` and I'm using three token types to parse that TimeSpan. Is there a shortcut for that? (I can open a new issue if you'd like)

**Comment by ChrisMissal** [comment]
Welp, I'm an idiot. I took another look at your example and realized I don't need to specify patterns more than once 🤦‍♂

**Comment by plioi** [comment]
If I remember right, the idea is the series of token-recognizing bits you pass to the base constructor are prioritized, so the main loop goes through those to see which is the first one that matches the next few characters of the input. For the most part the order won't have an impact since most tokens are wildly-different characters, but you could imaging a C# parser having to look for "==" operators before "=" operators.

**Comment by ChrisMissal** [comment]
That makes sense, thanks Patrick!
